// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/cardvalidator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCardRequest) Reset() {
	*x = ValidateCardRequest{}
	mi := &file_pkg_proto_cardvalidator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCardRequest) ProtoMessage() {}

func (x *ValidateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cardvalidator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCardRequest.ProtoReflect.Descriptor instead.
func (*ValidateCardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cardvalidator_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type ValidateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCardResponse) Reset() {
	*x = ValidateCardResponse{}
	mi := &file_pkg_proto_cardvalidator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCardResponse) ProtoMessage() {}

func (x *ValidateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cardvalidator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCardResponse.ProtoReflect.Descriptor instead.
func (*ValidateCardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cardvalidator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateCardResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateCardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *ValidateCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

var File_pkg_proto_cardvalidator_proto protoreflect.FileDescriptor

const file_pkg_proto_cardvalidator_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/cardvalidator.proto\x12\rcardvalidator\"6\n" +
	"\x13ValidateCardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\"j\n" +
	"\x14ValidateCardResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber2h\n" +
	"\rCardValidator\x12W\n" +
	"\fValidateCard\x12\".cardvalidator.ValidateCardRequest\x1a#.cardvalidator.ValidateCardResponseB!Z\x1fcredit-card-validator/pkg/protob\x06proto3"

var (
	file_pkg_proto_cardvalidator_proto_rawDescOnce sync.Once
	file_pkg_proto_cardvalidator_proto_rawDescData []byte
)

func file_pkg_proto_cardvalidator_proto_rawDescGZIP() []byte {
	file_pkg_proto_cardvalidator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cardvalidator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_cardvalidator_proto_rawDesc), len(file_pkg_proto_cardvalidator_proto_rawDesc)))
	})
	return file_pkg_proto_cardvalidator_proto_rawDescData
}

var file_pkg_proto_cardvalidator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_cardvalidator_proto_goTypes = []any{
	(*ValidateCardRequest)(nil),  // 0: cardvalidator.ValidateCardRequest
	(*ValidateCardResponse)(nil), // 1: cardvalidator.ValidateCardResponse
}
var file_pkg_proto_cardvalidator_proto_depIdxs = []int32{
	0, // 0: cardvalidator.CardValidator.ValidateCard:input_type -> cardvalidator.ValidateCardRequest
	1, // 1: cardvalidator.CardValidator.ValidateCard:output_type -> cardvalidator.ValidateCardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_cardvalidator_proto_init() }
func file_pkg_proto_cardvalidator_proto_init() {
	if File_pkg_proto_cardvalidator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_cardvalidator_proto_rawDesc), len(file_pkg_proto_cardvalidator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cardvalidator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cardvalidator_proto_depIdxs,
		MessageInfos:      file_pkg_proto_cardvalidator_proto_msgTypes,
	}.Build()
	File_pkg_proto_cardvalidator_proto = out.File
	file_pkg_proto_cardvalidator_proto_goTypes = nil
	file_pkg_proto_cardvalidator_proto_depIdxs = nil
}
